server.port=8082
football.data.path=C:/Users/saksh/OneDrive/Desktop/FDBMS/TikiDataProject/data
spring.application.name=football-website
spring.web.resources.static-locations=classpath:/static/
logging.level.com.football=INFO
